# Generated by Django 4.0.4 on 2023-01-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=20, verbose_name='RUT')),
                ('patologias', models.CharField(blank=True, max_length=150, verbose_name='Patologías')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(choices=[('ENFLAQUECIDO', 'Enflaquecido'), ('NORMAL', 'Normal'), ('SOBREPESO', 'Sobrepeso'), ('OBESIDAD GRADO I', 'Obesidad grado I'), ('OBESIDAD GRADO II', 'Obesidad grado II')], max_length=100, verbose_name='Diagnóstico nutricional')),
                ('peso', models.PositiveIntegerField()),
                ('talla', models.PositiveIntegerField()),
                ('imc', models.PositiveIntegerField()),
                ('active', models.BooleanField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingresos.paciente', verbose_name='Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha consulta')),
                ('hora', models.CharField(choices=[('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00')], max_length=11, verbose_name='Hora')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('CONTROL', 'Control')], max_length=100, verbose_name='Tipo consulta')),
                ('modalidad', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], max_length=20, verbose_name='Modalidad')),
                ('estado', models.CharField(choices=[('ANULADA', 'Anulada'), ('REALIZADA', 'Realizada'), ('PENDIENTE', 'Pendiente')], max_length=100, verbose_name='Estado')),
                ('active', models.BooleanField()),
                ('paciente', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='ingresos.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
