# Generated by Django 4.0.4 on 2023-01-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.CharField(choices=[('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00')], error_messages={'unique_for_date': 'La hora no está disponible'}, max_length=11, unique_for_date='fecha', verbose_name='Hora'),
        ),
    ]
